### ISSUE TITLE
 Feature Request: Remembering Network Drive Letters

### ISSUE THREAD

**Issue by stupmedia** [Redcat468/SMBguy#1]
Thank You for Your Great Work!

Currently, your software does not remember the drive letters associated with network drives. This missing feature can sometimes lead to difficulties in quickly retrieving the desired architecture.
We would like to propose the addition of a new feature that would allow the software to store in memory the drive letters assigned to network drives. The goal is to make it easier to retrieve the correct architecture with a single click.

Desired Functionality:
When a user connects to a network drive, the software should be able to detect the assigned drive letter for that drive. This drive letter would then be associated with the specific network drive in the software's internal memory.
The user could then select a network drive from a list, and the software would automatically assign the appropriate drive letter, simplifying access to the files and resources on that drive.

Reason for the Request:
This functionality would significantly enhance the efficiency of using the software, particularly in environments where multiple network drives are frequently used. It would reduce the risk of errors and save time when navigating network drives.
Please feel free to ask additional questions or request clarifications as needed. We look forward to your feedback and input on this proposal.

Stup.Corp

**Comment by Redcat468** [comment]
Fuck off ! 

 		Félix Abt

 		Directeur technique
cairnstudios.fr [http://cairnstudios.fr]

 		mobile: (+33) 7 86 59 78 57

 		***@***.***

 		[Facebook icon] [https://www.facebook.com/cairnprod/]  [Instagram
icon] [https://www.instagram.com/cairnproductions/]
